#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 30

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "g7dQ7/x9bB3W"
#define LAYER_STATE_16BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

